/******************************************************************************/
/***         Generated by IBExpert 2008.11.27 3/16/2009 2:26:02 PM          ***/
/******************************************************************************/



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE FW_OBJ (
    ID           A_BIG_ID NOT NULL,
    CAPTION      A_STR_SHORT,
    KEY_FIELD    A_STR_SHORT,
    TABLE_NAME   A_STR_SHORT,
    CLASS_NAME   A_STR_SHORT,
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE FW_OBJ_PHIEU (
    OBJ_ID    A_BIG_ID NOT NULL,
    PHIEU_ID  A_BIG_ID NOT NULL
);

CREATE TABLE FW_PHIEU (
    ID               A_BIG_ID NOT NULL,
    CAPTION          A_STR_SHORT,
    KEY_FIELD        A_STR_SHORT,
    OBJ_FIELD        A_STR_SHORT,
    MA_FIELD_NAME    A_STR_SHORT,
    NGAY_TAO_FN      A_STR_SHORT,
    NGAY_CN_FN       A_STR_SHORT,
    TABLE_NAME       A_STR_SHORT,
    CLASS_NAME       A_STR_SHORT,
    FORM_CLASS_NAME  A_STR_SHORT
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE FW_OBJ ADD CONSTRAINT PK_FW_OBJ PRIMARY KEY (ID);
ALTER TABLE FW_OBJ_PHIEU ADD CONSTRAINT PK_FW_OBJ_PHIEU PRIMARY KEY (OBJ_ID, PHIEU_ID);
ALTER TABLE FW_PHIEU ADD CONSTRAINT PK_FW_PHIEU PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE FW_OBJ_PHIEU ADD CONSTRAINT FK_FW_OBJ_PHIEU_1 FOREIGN KEY (OBJ_ID) REFERENCES FW_OBJ (ID) ON DELETE CASCADE;
ALTER TABLE FW_OBJ_PHIEU ADD CONSTRAINT FK_FW_OBJ_PHIEU_2 FOREIGN KEY (PHIEU_ID) REFERENCES FW_PHIEU (ID) ON DELETE CASCADE;
