/******************************************************************************/
/***          Generated by IBExpert 2008.11.27 4/8/2009 4:28:27 PM          ***/
/******************************************************************************/



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE DM_TRAM (
    ID           A_BIG_ID NOT NULL,
    MA_TRAM      A_STR_SHORT,
    NAME         A_STR_MEDIUM,
    ADDRESS      A_STR_MEDIUM,
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE DM_TUYEN (
    ID           A_BIG_ID NOT NULL,
    MA_TUYEN     A_STR_SHORT,
    NAME         A_STR_MEDIUM,
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE TUYEN_CT (
    TUYEN_ID  A_BIG_ID NOT NULL,
    TRAM_ID   A_BIG_ID NOT NULL,
    NOI_DUNG  A_STR_VERY_LONG,
    AM_THANH  A_IMAGE
);



/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE DM_TRAM ADD CONSTRAINT UNQ1_DM_TRAM UNIQUE (MA_TRAM);
ALTER TABLE DM_TRAM ADD CONSTRAINT UNQ2_DM_TRAM UNIQUE (NAME);
ALTER TABLE DM_TUYEN ADD CONSTRAINT UNQ1_DM_TUYEN UNIQUE (MA_TUYEN);
ALTER TABLE DM_TUYEN ADD CONSTRAINT UNQ2_DM_TUYEN UNIQUE (NAME);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE DM_TRAM ADD CONSTRAINT PK_DM_TRAM PRIMARY KEY (ID);
ALTER TABLE DM_TUYEN ADD CONSTRAINT PK_DM_TUYEN PRIMARY KEY (ID);
ALTER TABLE TUYEN_CT ADD CONSTRAINT PK_TUYEN_CT PRIMARY KEY (TUYEN_ID, TRAM_ID);
